server:
  port: ${CUSTOM_SERVER_PORT:8762}

### Eureka Client configuration
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST_SERVER}
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    refresh:
      enable: true
      
jwt:
  auth:
    converter:
      resource-id: ${AUTH_CONVERTER_RESOURCEID}
      principal-attribute: ${AUTH_CONVERTER_PRINCIPAL_ATRIBUTE}

spring:
  security:
     oauth2:
       resourceserver:
         jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
           
### Cloud Gateway configuration
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: license-write-service
          uri: lb://license-write-service
          predicates:
            - Path=/api/v1/licencia/**
            - Header=X-Request-Id, write
            - Method=POST,DELETE,PUT
        - id: license-read-service
          uri: lb://license-read-service
          predicates:
            - Path=/api/v1/licencia/**
            - Header=X-Request-Id, read
            - Method=GET
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/v1/auditoria/**

### Actuator info (/actuator/info)
info:
  app:
    app-name: Cloud Gateway Microservice
    description: Microservicio para el ruteo de los microservicios
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
